name: Run Test

on:
  push:
    branches:
      - '**'
      - '!main'
    paths:
      - '**.go'
  pull_request:
    branches:
      - develop
      - main
    types:
      - opened
    paths:
      - '**.go'
  workflow_dispatch:

jobs:
  go-test:

    runs-on: ubuntu-latest
    timeout-minutes: 300

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go 1.22.2
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.2
          cache: true

      - name: Run checks
        uses: golangci/golangci-lint-action@v5
        with:
          version: latest
          args: --timeout=5m

