services:
  # api
  api:
    image: yubinbango-api:latest
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      DATA_DIR_PATH: data/output
      BASIC_AUTH_USER: user
      BASIC_AUTH_PASSWORD: pass
    volumes:
      - "./data:/data"
